spring.application.name=FinanceManager
server.port=9090

# PostgreSQL datasource (configure credentials via environment variables or override)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finance_manager}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT settings
application.security.jwt.secret-key=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=86400000

fns.api.token=${FNS_API_TOKEN:}
spring.main.web-application-type=servlet



# Yandex OAuth2
spring.security.oauth2.client.registration.yandex.client-id=${YANDEX_CLIENT_ID:0785709585674ea7ac1fe9f16c1eab51}
spring.security.oauth2.client.registration.yandex.client-secret=${YANDEX_CLIENT_SECRET:f77498e9a5cf4cf69ff3649aea2a779c}
spring.security.oauth2.client.registration.yandex.client-name=Yandex
spring.security.oauth2.client.registration.yandex.provider=yandex
spring.security.oauth2.client.registration.yandex.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.yandex.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.provider.yandex.authorization-uri=https://oauth.yandex.ru/authorize
spring.security.oauth2.client.provider.yandex.token-uri=https://oauth.yandex.ru/token
spring.security.oauth2.client.provider.yandex.user-info-uri=https://login.yandex.ru/info?format=json
spring.security.oauth2.client.provider.yandex.user-name-attribute=id